---
title: "day4exercise"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r set up}
library(rvest)
library(readr)
library(dplyr)
library(janitor)

webpage <- read_html("https://www.pwrc.usgs.gov/bbl/manual/speclist.cfm")

tbls <- html_nodes(webpage, "table") %>% 
    html_table(fill = TRUE)

species <- tbls[[1]] %>% 
    clean_names() %>% 
    select(alpha_code, common_name) %>% 
    mutate(alpha_code = tolower(alpha_code))

```

read in data

```{r read in data}
pred = read_csv("https://arcticdata.io/metacat/d1/mn/v2/object/urn%3Auuid%3A9ffec04c-7e2d-41dd-9e88-b6c2e8c4375e")
nest = read_csv("https://arcticdata.io/metacat/d1/mn/v2/object/urn%3Auuid%3A982bd2fc-4edf-4da7-96ef-0d11b853102d")

summary(nest)
summary(species)
```

make function

```{r}
common.name = function(df, species){
    return_df = left_join(df, species, by = c("species" = "alpha_code"))
    return(return_df)
}
```

add common names

```{r}
nest.cn = common.name(nest, species)
pred.cn = common.name(pred, species)
```

total pred by year

```{r}
pred.count = pred.cn %>% 
  group_by(year, common_name) %>% 
  summarise(total.pred = sum(count, na.rm = TRUE))
```

plot year by total predators

```{r}
ggplot(pred.count, aes(x = year, y = total.pred, color = common_name)) +
  geom_line() +
  geom_point() +
  labs(x = "Year", y = "Number of Predators", color = "Species") 
  
```



```{r}
nest.pred = nest.cn %>% 
  group_by(year, common_name) %>% 
  summarise(nest.eaten = sum(number_eggs_predated, na.rm = TRUE))
```

```{r}
pred.and.eaten = left_join(pred.count, nest.pred, by = c("year"))
```


```{r}
ggplot(pred.and.eaten, aes(x = total.pred, y = nest.eaten, color = common_name.x)) +
  geom_point() +
  facet_wrap(~common_name.y, scales = "free_y") +
  
  labs(x = "Number of Predators", y = "Number of Nests Eaten", color = "Species") 
```

